"""Initial migration

Revision ID: d4be6d6a9dd3
Revises: 
Create Date: 2025-12-15 15:02:29.169655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4be6d6a9dd3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pull_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_owner', sa.String(length=255), nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('head_sha', sa.String(length=40), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('pr_url', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_requests_head_sha'), 'pull_requests', ['head_sha'], unique=False)
    op.create_index(op.f('ix_pull_requests_pr_number'), 'pull_requests', ['pr_number'], unique=False)
    op.create_index(op.f('ix_pull_requests_repo_name'), 'pull_requests', ['repo_name'], unique=False)
    op.create_index(op.f('ix_pull_requests_repo_owner'), 'pull_requests', ['repo_owner'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.Integer(), nullable=False),
    sa.Column('coolify_deployment_id', sa.String(length=255), nullable=True),
    sa.Column('coolify_application_id', sa.String(length=255), nullable=True),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED', 'CANCELLED', name='deploymentstatus'), nullable=False),
    sa.Column('deployment_url', sa.String(length=512), nullable=True),
    sa.Column('logs_url', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('full_logs', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_commit_sha'), 'deployments', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_deployments_coolify_application_id'), 'deployments', ['coolify_application_id'], unique=False)
    op.create_index(op.f('ix_deployments_coolify_deployment_id'), 'deployments', ['coolify_deployment_id'], unique=True)
    op.create_index(op.f('ix_deployments_pr_id'), 'deployments', ['pr_id'], unique=False)
    op.create_index(op.f('ix_deployments_status'), 'deployments', ['status'], unique=False)
    op.create_table('pr_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(length=255), nullable=False),
    sa.Column('comment_type', sa.String(length=50), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pr_comments_comment_id'), 'pr_comments', ['comment_id'], unique=True)
    op.create_index(op.f('ix_pr_comments_pr_id'), 'pr_comments', ['pr_id'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('ANALYZE', 'SHOW_LOGS', 'APPLY_FIX', 'RERUN', name='actiontype'), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('command_text', sa.Text(), nullable=False),
    sa.Column('comment_id', sa.String(length=255), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('result_message', sa.Text(), nullable=True),
    sa.Column('files_modified', sa.JSON(), nullable=True),
    sa.Column('patch_content', sa.Text(), nullable=True),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_action_type'), 'actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_actions_deployment_id'), 'actions', ['deployment_id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('failure_category', sa.Enum('ENV_VAR_MISSING', 'PORT_MISMATCH', 'DEPENDENCY_ERROR', 'BUILD_FAILURE', 'RUNTIME_CRASH', 'HEALTHCHECK_FAILURE', 'DATABASE_CONNECTION', 'UNKNOWN', name='failurecategory'), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('llm_provider', sa.String(length=50), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('llm_prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_completion_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_raw_response', sa.Text(), nullable=True),
    sa.Column('patterns_matched', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_deployment_id'), 'analyses', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_analyses_failure_category'), 'analyses', ['failure_category'], unique=False)
    op.create_index(op.f('ix_analyses_status'), 'analyses', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_status'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_failure_category'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_deployment_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_actions_deployment_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_action_type'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_pr_comments_pr_id'), table_name='pr_comments')
    op.drop_index(op.f('ix_pr_comments_comment_id'), table_name='pr_comments')
    op.drop_table('pr_comments')
    op.drop_index(op.f('ix_deployments_status'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_pr_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_coolify_deployment_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_coolify_application_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_commit_sha'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_pull_requests_repo_owner'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_repo_name'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_pr_number'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_head_sha'), table_name='pull_requests')
    op.drop_table('pull_requests')
    # ### end Alembic commands ###
